[domain]
    name='bpp'
    [domain.args]
        db_path = "datasets_dnc/hard_parsed.json"
        dataset_name = "BPP_14"

[crossover]
    name='kpoint'
    [crossover.args]
        probability = 0.5
        k = 1
        arity = 2

[mutation]
    name='uniform'
    [mutation.args]
        probability = 0.5
        probability_for_each = 0.1
        arity = 1

[evolution]
    max_generation = 50
    population_size = 100
